server-name: 'TomorrowLand'
color: '§b'
cooldown-time: 10

global-speaker:
  name: "&e&lLoa thế giới"
  lore:
    - "&a&oDùng để chat toàn server"
  type: "PAPER"
#  durability: 0
#  enchant:
#   - DURABILITY:1
#   - KNOCKBACK:3
#  flag: