name: Speaker
version: ${project.version}
main: tranlong5252.speakers.Speaker
api-version: 1.16
authors: [ tranlong5252 ]
commands:
  loa:
    description: Chat toàn server
  getloa:
    description: Lấy loa
    permission: speaker.getspeaker
  ignoreloa:
    permission: speaker.ignore
  loareload:
    description: Reload
    permission: speaker.reload
