name: Speaker
version: ${project.version}
main: tranlong5252.speakers.Speaker
api-version: 1.12
authors: [ tranlong5252 ]
commands:
  loa:
    description: Chat toàn server
  getloa:
    description: Lấy loa